name: drand
base: core20
version: '1.2.7'
summary: Distributed randomness beacon
description: |
  Linked drand nodes collectively produce publicly verifiable, unbiased and
  unpredictable random values at fixed intervals using bilinear pairings and
  threshold cryptography.

grade: devel
confinement: devmode

apps:
  drand:
    command: bin/drand

parts:
  drand:
    plugin: go
    # go-importpath: github.com/drand/drand
    source: .
    source-type: git
    build-packages:
      - gcc
